name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: flashlearn
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t flashlearn-app:ci .

      # Run the app container
      - name: Run Spring Boot app
        run: |
          docker run -d \
            --name flashlearn-app \
            --env SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/flashlearn \
            --env SPRING_DATASOURCE_USERNAME=root \
            --env SPRING_DATASOURCE_PASSWORD=root \
            --env SPRING_MAIL_HOST=localhost \
            --env SPRING_MAIL_PORT=1025 \
            -p 8080:8080 flashlearn-app:ci

      # Wait for app to be ready
      - name: Wait for Spring Boot
        run: sleep 20

      # Optionally, run integration tests
      - name: Run tests
        run: docker exec flashlearn-app ./mvnw test || mvn test
