name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL..."
          for i in {1..20}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' flashlearn-mysql)
            if [ "$STATUS" == "healthy" ]; then break; fi
            sleep 3
          done

      - name: Wait for App
        run: |
          echo "Waiting for Spring Boot..."
          for i in {1..20}; do
            if curl -s http://localhost:8080/hello; then break; fi
            sleep 3
          done

      - name: Run Tests
        run: |
          APP_CONTAINER=$(docker ps -q -f name=flashlearn-app)
          docker exec $APP_CONTAINER ./mvnw test || mvn test

      - name: Tear down
        if: always()
        run: docker compose down
