name: Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      # Step 4: Build Docker image
      - name: Build app image
        run: docker compose build

      # Step 5: Start all containers (MySQL, Mailhog, App)
      - name: Start containers
        run: docker compose up -d

      # Step 6: Wait for MySQL and App to be ready
      - name: Wait for services
        run: |
          echo "⏳ Waiting for MySQL to become healthy..."
          for i in {1..15}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' flashlearn-mysql)
            if [ "$STATUS" == "healthy" ]; then
              echo "✅ MySQL is healthy!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

          echo "⏳ Waiting for Spring Boot app to start..."
          for i in {1..15}; do
            if curl -s http://localhost:8080/hello; then
              echo "✅ App is ready!"
              break
            fi
            echo "Waiting for app..."
            sleep 5
          done

      # Step 7: Run tests inside the app container
      - name: Run Tests in container
        run: |
          APP_CONTAINER=$(docker ps -q -f name=flashlearn-app)
          echo "Running tests inside $APP_CONTAINER"
          docker exec $APP_CONTAINER ./mvnw test || mvn test

      # Step 8: Print logs on failure for debugging
      - name: Print container logs if failed
        if: failure()
        run: |
          echo "==== APP LOGS ===="
          docker logs flashlearn-app || true
          echo "==== MYSQL LOGS ===="
          docker logs flashlearn-mysql || true
          echo "==== MAILHOG LOGS ===="
          docker logs flashlearn-mailhog || true

      # Step 9: Stop containers
      - name: Stop containers
        if: always()
        run: docker compose down
