name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t flashlearn-app:ci .

      # Step 5: Start Mailhog container
      - name: Start Mailhog
        run: docker run -d --name flashlearn-mailhog -p 1025:1025 -p 8025:8025 mailhog/mailhog

      # Step 6: Run Spring Boot container
      - name: Run Spring Boot app
        run: docker run -d --name flashlearn-app-ci -p 8080:8080 \
              -e SPRING_MAIL_HOST=flashlearn-mailhog \
              -e SPRING_MAIL_PORT=1025 \
              flashlearn-app:ci

      # Step 7: Wait for app to start
      - name: Wait for Spring Boot
        run: docker run -d --name flashlearn-app-ci -p 8080:8080 -e SPRING_MAIL_HOST=flashlearn-mailhog -e SPRING_MAIL_PORT=1025 flashlearn-app:ci


      # Step 8: Run tests
      - name: Run Tests
        run: |
          docker exec $(docker ps -q -f ancestor=flashlearn-app:ci) ./mvnw test || mvn test
